# Generated by Django 5.2.16 on 2026-07-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('truck_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=15, unique=True, verbose_name='Placa')),
                ('tipo', models.CharField(choices=[('Camioneta', 'Camioneta'), ('Bus', 'Bus'), ('Camión', 'Camión'), ('Volquete', 'Volquete')], max_length=20, verbose_name='Tipo de Vehículo')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad (pasajeros/toneladas)')),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('En servicio', 'En servicio'), ('En mantenimiento', 'En mantenimiento'), ('De baja', 'De baja')], default='Disponible', max_length=20, verbose_name='Estado')),
                ('revision_tecnica_vigente', models.BooleanField(default=True, verbose_name='Revisión Técnica Vigente')),
                ('seguro_vigente', models.BooleanField(default=True, verbose_name='Seguro Vigente')),
                ('homologacion', models.CharField(blank=True, max_length=100, verbose_name='Código de Homologación')),
                ('mantenimiento_programado', models.DateField(blank=True, null=True, verbose_name='Mantenimiento Programado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['placa'],
            },
        ),
    ]
