# Generated by Django 5.2.16 on 2026-07-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=150, verbose_name='Cliente')),
                ('fecha_servicio', models.DateField(verbose_name='Fecha de Servicio')),
                ('hora_servicio', models.TimeField(verbose_name='Hora de Servicio')),
                ('origen', models.CharField(max_length=200, verbose_name='Origen')),
                ('destino', models.CharField(max_length=200, verbose_name='Destino')),
                ('tipo_servicio', models.CharField(choices=[('Traslado de personal', 'Traslado de personal'), ('Traslado de carga', 'Traslado de carga'), ('Traslado mixto', 'Traslado mixto')], max_length=50, verbose_name='Tipo de Servicio')),
                ('prioridad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=20, verbose_name='Prioridad')),
                ('tipo_vehiculo_requerido', models.CharField(choices=[('Camioneta', 'Camioneta'), ('Bus', 'Bus'), ('Camión', 'Camión'), ('Volquete', 'Volquete')], max_length=50, verbose_name='Tipo de Vehículo Requerido')),
                ('estado_solicitud', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Asignada', 'Asignada'), ('Reprogramada', 'Reprogramada'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20, verbose_name='Estado de Solicitud')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Solicitud de Servicio',
                'verbose_name_plural': 'Solicitudes de Servicio',
                'ordering': ['-fecha_servicio', '-hora_servicio'],
            },
        ),
    ]
