# Generated by Django 5.2.16 on 2026-07-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('driver_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('licencia', models.CharField(max_length=20, unique=True, verbose_name='Número de Licencia')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupado', 'Ocupado'), ('No apto', 'No apto'), ('De baja', 'De baja')], default='Disponible', max_length=20, verbose_name='Estado')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
