# Generated by Django 5.2.16 on 2026-07-22 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGerencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, help_text='Ej.: "Dashboard gerencial - Sprint 5"', max_length=200, verbose_name='Descripción')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='reportes_gerenciales/', verbose_name='Reporte PDF')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_gerenciales', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Reporte gerencial',
                'verbose_name_plural': 'Reportes gerenciales',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='CapturaReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='reportes_gerenciales/capturas/', verbose_name='Captura de pantalla')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capturas', to='dashboard.reportegerencial', verbose_name='Reporte')),
            ],
            options={
                'verbose_name': 'Captura de reporte',
                'verbose_name_plural': 'Capturas de reporte',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
