# Generated by Django 5.2.16 on 2026-07-14 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoConductor',
            fields=[
                ('document_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('Licencia de conducir', 'Licencia de conducir'), ('Homologación', 'Homologación'), ('Examen médico', 'Examen médico'), ('Autorización', 'Autorización')], max_length=50, verbose_name='Tipo de Documento')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('estado_documento', models.CharField(choices=[('Vigente', 'Vigente'), ('Por vencer', 'Por vencer'), ('Vencido', 'Vencido')], default='Vigente', max_length=20, verbose_name='Estado de Documento')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos_conductores/', verbose_name='Archivo Adjunto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='drivers.conductor', verbose_name='Conductor')),
            ],
            options={
                'verbose_name': 'Documento de Conductor',
                'verbose_name_plural': 'Documentos de Conductor',
                'ordering': ['-fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoVehiculo',
            fields=[
                ('document_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('Revisión técnica', 'Revisión técnica'), ('Seguro', 'Seguro'), ('Homologación', 'Homologación'), ('Permiso de operación', 'Permiso de operación')], max_length=50, verbose_name='Tipo de Documento')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('estado_documento', models.CharField(choices=[('Vigente', 'Vigente'), ('Por vencer', 'Por vencer'), ('Vencido', 'Vencido')], default='Vigente', max_length=20, verbose_name='Estado de Documento')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos_vehiculos/', verbose_name='Archivo Adjunto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='trucks.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Documento de Vehículo',
                'verbose_name_plural': 'Documentos de Vehículo',
                'ordering': ['-fecha_vencimiento'],
            },
        ),
    ]
