# Generated by Django 5.2.16 on 2026-07-14 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('service_requests', '0001_initial'),
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('assignment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado_asignacion', models.CharField(choices=[('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Observada', 'Observada'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=20, verbose_name='Estado de Asignación')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación / Motivo')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='drivers.conductor', verbose_name='Conductor')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='service_requests.solicitudservicio', verbose_name='Solicitud de Servicio')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='trucks.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['-fecha_asignacion'],
            },
        ),
    ]
