# Generated by Django 5.2.16 on 2026-07-14 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('alert_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_alerta', models.CharField(choices=[('Documento vencido', 'Documento vencido'), ('Documento por vencer', 'Documento por vencer'), ('Vehículo en mantenimiento', 'Vehículo en mantenimiento'), ('Conductor no apto', 'Conductor no apto')], max_length=50, verbose_name='Tipo de Alerta')),
                ('nivel_riesgo', models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=20, verbose_name='Nivel de Riesgo')),
                ('estado_alerta', models.CharField(choices=[('Activa', 'Activa'), ('Resuelta', 'Resuelta')], default='Activa', max_length=20, verbose_name='Estado de Alerta')),
                ('mensaje', models.CharField(max_length=255, verbose_name='Mensaje de Alerta')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('documento_conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='documents.documentoconductor', verbose_name='Documento de Conductor')),
                ('documento_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='documents.documentovehiculo', verbose_name='Documento de Vehículo')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
